.master_on_push: &master_on_push
  - if: '($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "push") && $CI_COMMIT_REF_NAME == "ci"'
    when: on_success
  - if: '$CI_COMMIT_TAG'
    when: never

.on_tag: &on_tag
  - if: '($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "push") && $CI_COMMIT_TAG '
    when: on_success

.set_up_cluster: &set_up_cluster
  - k3d cluster create
  - kubectl get node
  - k3d kubeconfig merge --all -d
  - kubectl config view

stages:
  - test
  - build
  - release




test:
  image: registry.gitlab.com/onecommons/unfurl-test-docker-image:tf_0.13.6-helm_3.3.4-kubectl_1.17.14-k3d_3.4.0
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    TOX_TESTENV_PASSENV: DOCKER_HOST
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
    LC_CTYPE: C.UTF-8
  rules: *master_on_push
  stage: test
  script:
    - *set_up_cluster
    - tox
  tags:
    - kubernetes


build:
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  rules: *master_on_push
  stage: build
  script:
    - 'docker build -t registry.gitlab.com/onecommons/unfurl:${CI_COMMIT_SHA} -f ./docker/Dockerfile .'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.gitlab.com/onecommons/unfurl:${CI_COMMIT_SHA}
  tags:
      - kubernetes

release:
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  rules: *on_tag
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - 'docker pull registry.gitlab.com/onecommons/unfurl:${CI_COMMIT_SHA}'
    - docker logout $CI_REGISTRY
    - 'docker tag  registry.gitlab.com/onecommons/unfurl:${CI_COMMIT_SHA} onecommons/unfurl:${CI_COMMIT_TAG}'
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
    - docker push onecommons/unfurl:${CI_COMMIT_TAG}
  tags:
    - kubernetes