language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - TOX_SKIP_ENV=.+(docker|lock)
    - tf_version=0.12.29
    - helm_version=3.3.4
    - UNFURL_TEST_KUBECONTEXT=k3d-default
before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
  - wget https://get.helm.sh/helm-v"$helm_version"-linux-amd64.tar.gz
  - tar -zxvf helm-v"$helm_version"-linux-amd64.tar.gz
  - sudo mv linux-amd64/helm /usr/local/bin/helm
  - wget https://storage.googleapis.com/kubernetes-release/release/v1.17.14/bin/linux/amd64/kubectl
  - wget https://github.com/rancher/k3d/releases/download/v3.4.0/k3d-linux-amd64
  - chmod +x k3d-linux-amd64 kubectl
  - sudo mv k3d-linux-amd64 /usr/local/bin/k3d
  - sudo mv kubectl /usr/local/bin
  - k3d --version
install: pip install tox-travis
script:
  - k3d cluster create "$UNFURL_TEST_KUBECONTEXT"
  - kubectl get node
  - k3d kubeconfig merge --all -d
  - kubectl config view
  - tox
