name: Deploy to dockerhub and pypi

on:  
  push:
    branches: []
    tags:
      - '*'
jobs:
  deploy_dockerhub:
#    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    env:
      PYPI_USER: "__token__"
      DOCKERHUB_USER: "ocbuilds"
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_HUB }}
      - name: fetch repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Get the tag name
        id: get_tag_name
        run: echo "::set-output name=tag::"`git describe --contains --always`
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          push: true
          tags: |
             onecommons/unfurl:latest
             onecommons/unfurl:${{ steps.get_tag_name.outputs.tag }}
